Fair Squares W3F grant proposal
Fair-Squares/Grants-Program pull request #1
Opened 2022-05-24 19:00 UTC by ilhanu

Think we are ready to soon to create a PR in the w3f repo, we just need proof-read the grant proposal and review the parts we write. 

Parts that are missing still
- Visualisation for **milestone 5** 
-  ETH address for grant payments

@ndkazu when you have time can you please re-check the state-diagram and make it coherent with all the naming in the proposal. 

@letodunc added all the sequence diagrams as links in text and please also proof-read and review it.

2022-05-25 13:18 UTC, ndkazu requested changes
Corrected a few type misses, and submitted the updated version of the development state diagram

2022-05-25 21:20 UTC, ilhanu commented on applications/fair_squares.md
> +
thanks for the update!

2022-05-25 21:21 UTC, ilhanu reviewed
Thanks for the review @ndkazu added all the changes

2022-05-26 10:09 UTC, ilhanu commented
Added review Mahir

2022-05-26 16:40 UTC, letodunc requested changes

2022-05-26 16:40 UTC, letodunc commented on applications/fair_squares.md
> +For our social mission to be succesful we require several actions on-chain, such as voting, selection of funds, governing and reccuring payments. We are looking to build a feeless parachain while get
For our mission to be successful

2022-05-26 16:40 UTC, letodunc commented on applications/fair_squares.md
> +For our social mission to be succesful we require several actions on-chain, such as voting, selection of funds, governing and reccuring payments. We are looking to build a feeless parachain while get
We believe that the parachain functionality

2022-05-26 16:40 UTC, letodunc commented on applications/fair_squares.md
> +| 2. | **pallet-voting**| We will customizethe known frame pallets such as `democracy` and `collective` pallet and devise to fit the voting structures that are required for FS. The **housing-council*
We will customize the known frame pallet

2022-05-30 11:55 UTC, ilhanu commented on applications/fair_squares.md
> +For our social mission to be succesful we require several actions on-chain, such as voting, selection of funds, governing and reccuring payments. We are looking to build a feeless parachain while get
I won't change this, so make the social mission awareness.

2022-05-30 11:55 UTC, ilhanu commented
changed comments @letodunc

2022-05-30 11:57 UTC, merged